import type { Metadata } from "next";
import styles from "./store.module.css";
import CategoryList from "../components/CategoryList/CategoryList";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCategory() {
  const res = await fetch(`http://localhost:1337/api/product-categories`);

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await getCategory();

  return (
    <main>
      <div className={`container ${styles.storeLayout}`}>
        <CategoryList list={data} />
        <div className={styles.storeChildren}>{children}</div>
      </div>
    </main>
  );
}
