import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import HeaderMenu from "@/parts/HeaderMenu/HeaderMenu";
import Footer from "@/parts/Footer/Footer";
import "dotenv/config";

const inter = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
